### ISSUE TITLE
new version gives error when compling in linux

### ISSUE THREAD

**Issue by eagalpern** [debbiemarkslab/plmc#12]
Hi, 
compiling this new version in linux (with ot without openmp) yelds an error:

In file included from src/plm.c:15:
src/include/plm.h:106:20: error: field ‘start’ has incomplete type
  106 |     struct timeval start;  // sys/time.h
      |                    ^~~~~
In file included from src/include/weights.h:4,
                 from src/weights.c:6:
src/include/plm.h:106:20: error: field ‘start’ has incomplete type
  106 |     struct timeval start;  // sys/time.h
      |                    ^~~~~
In file included from src/main.c:5:
src/include/plm.h:106:20: error: field ‘start’ has incomplete type
  106 |     struct timeval start;  // sys/time.h

**Comment by LDeng0205** [comment]
I have just encountered the same issue. You can fix this by adding #include <sys/time.h> in src/include/plm.h
