### ISSUE TITLE
0 valid sequences

### ISSUE THREAD

**Issue by yazhinia** [debbiemarkslab/plmc#2]
I try to run plmc for RNA sequence. Dataset contains 11870 sequences (derived from RFAM database). Input file is fasta format. While running plmc, I always get an error saying that "0 valid sequences". What could be the reason to get such error though MSA contains divergent sequences. Please suggest me to rectify this issue.

**Comment by mmagnus** [comment]
Can you show the head of your alignment? Are you using `-` for gaps or `.` . I think I had a similar problem when there were `-` in my alignments for gaps.

**Comment by yazhinia** [comment]
`>ABGY01008196.1/259-62
CACCCU---U--C-U------C-G-G--C-C------U-C-U----U-------------
------------------------------G--G--C-U--A-----A-G---A-U--C-
--AA------------UUU-------G------U-----A-----G-----U-----A--
-------C---C----U--G----U----U-------C------U-----U--A--U--C
---A-G----C--G-U---G----A----U---A--G-----------------------
------------------------------------------------------------
-----------------C----U---G---A---U-A-----U------G--GU--C--U
--CA-----A-U------------------------------------------------
---------------------A--G--A--G-G--CC--------------UUAU-----
--------CAAUUUCAC----A------A-A--A--A-U-U-U-U-U-G-AU-AGGG---
-------G-A-A-A-G-GA-U-AAUU-------------UGA-A--GC------U-----
U-----------------------------------------------------------
---------------------------G-C-U-U--CUU-------------------AU
A-AC-C--U-U---U--C-------G-------C----GC--G-U-U-G--C--------
--C-U-U--------A-C--C-----C--------U---U-------G----C-A--C--
UAA------A--------------------------------------------------
----------------------------G-G-U-----U--UG----UA--------C-A
--G--U---GCACCCUUA
>AE014186.2/1461495-1461298
CACCCU---U--C-U------C-G-G--C-C------U-C-U----U-------------
`
script is `plmc -a .AGUC file.fasta`

**Comment by mmagnus** [comment]
It seems that it will do the work:

```
plmc -a -AGUC alignment/pistol.mfa
654 valid sequences out of 654
110 sites
Effective number of samples: 94.3	(80% identical neighborhood = 1.000 samples)
iter	time	cond	fx	-loglk	||h||	||e||
1	1.0	19.96	7523.9	7349.8	32.8	1.3
2	1.5	15.20	7010.5	6284.1	32.9	2.7
^Z
```

**Comment by yazhinia** [comment]
Is your input file is fasta format with "-" character representing gaps? If that is the case, why should I get an error?

**Comment by mmagnus** [comment]
Yes, plmc has to know the alphabet.

**Comment by yazhinia** [comment]
`0 valid sequences out of 208 
229 sites
Effective number of samples: 0.0	(80% identical neighborhood = 1.000 samples)
Gradient optimization: No detected error`
Again getting same error irrespective of various input file. Very perplexed.

**Comment by mmagnus** [comment]
Can you type the command line that you are using for this?

**Comment by yazhinia** [comment]
Thank you for your response. I figured out. plmc needs single line multiple sequence fasta format with gap character ".".  Now it is working fine.

**Comment by jingraham** [comment]
Glad that this could work out and thanks for the pointers, @mmagnus!
Closing for now.
